# projects/etl_base_project/src/db/base.py
from __future__ import annotations
from typing import Any, Dict, Iterable, List, Optional, Protocol, Tuple

class Dialect(Protocol):
    name: str

    # Identifiers
    def qident(self, ident: str) -> str: ...
    def qualify(self, schema: str, table: str) -> str: ...

    # SQL parçaları
    def wrap_sql_source(self, sql: str) -> str: ...
    def limit_clause(self, n: int) -> str: ...
    def offset_clause(self, n: int) -> str: ...
    def order_by(self, order_by: Optional[str]) -> str: ...

    # Metadata
    def column_datatype_query(self) -> str: ...
    def column_list_query(self) -> str: ...
    def min_max_sql(self, schema: str, table: str, column: str, where: Optional[str]) -> str: ...
    def distinct_sql(self, schema: str, table: str, column: str, where: Optional[str], limit: Optional[int]) -> str: ...

    # Literal ve predicate üretimi (CAST etmiyoruz → literal’i tipe göre yazıyoruz)
    def normalize_type(self, db_type: str) -> str: ...
    def literal_for_type(self, val: Any, db_type: str) -> str: ...
    def pred_eq(self, schema: str, table: str, column: str, val: Any, col_type: str) -> str: ...
    def pred_ge_lt(self, schema: str, table: str, column: str, lo: Any, hi: Any, col_type: str) -> str: ...
    def pred_ge_le(self, schema: str, table: str, column: str, lo: Any, hi: Any, col_type: str) -> str: ...

    # Pencere/NTILE ve mod operatörü SQL farkları
    def ntile_range_sql(self, schema: str, table: str, column: str, parts: int, where: Optional[str]) -> str: ...
    def mod_expr(self, column: str, parts: int, remainder: int) -> str: ...

class Driver(Protocol):
    dialect: Dialect

    # bağlantı
    def connect(self, conf: Dict[str, Any]): ...
    def close(self, conn): ...

    # yürütme
    def fetchall(self, conn, sql: str, params: Optional[Tuple]=None) -> Tuple[List[Tuple], List[str]]: ...
    def server_cursor_iter(self, conn, sql: str, arraysize: int) -> Iterable[List[Dict[str, Any]]]: ...

    # kopyalama (varsa hızlı yol), yoksa CSV fallback
    def copy_to_filelike(self, conn, inner_select_sql: str, file_obj, *, binary: bool) -> None: ...

    # metadata
    def get_column_types(self, conn, schema: str, table: str) -> Dict[str, str]: ...

