SELECT 
    CRD.SODEXO_CARD_NO,
    PPUPD.VALUE AS SERVICE_ID,
    CA.TTL_HST_BAL_CURR, 
    CRD.CARD_STAT_CODE,
    TO_CHAR(CRD.LAST_TXN_DATE) || LPAD(CRD.LAST_TXN_TIME, 6, '0') AS LAST_TXN_DATETIME,
    TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') AS sorgu_tarihi
FROM OC_CRD.CRD_CARD CRD
JOIN OC_CRD.CRD_CARD_ACCOUNT_BALANCE_REL CCABR ON CRD.MAIN_ACCOUNT_NO = CCABR.MAIN_ACCOUNT_NO
JOIN OC_CRD.CRD_CARD_ACCOUNT CA ON CA.ACCOUNT_NO = CCABR.ACCOUNT_NO AND CA.MBR_ID = CCABR.MBR_ID
JOIN OC_PRM.PRM_PREPAID_USAGE_PROFILE_DTL PPUPD ON CCABR.PROFILE_CODE = PPUPD.PROFILE_CODE AND CCABR.MBR_ID = PPUPD.MBR_ID
WHERE CRD.STATUS = 1
AND CCABR.STATUS = 1
AND CA.STATUS = 1
AND PPUPD.STATUS = 1
AND CCABR.PROFILE_CODE != '122' 
AND PPUPD.VALUE != '1143'
